exports.products = [
  {
    id: 1,
    photo: "/images/black-tee.webp",
    title: "Black college t-shirt",
    caption: "Manufactured by A&D",
    price: 7,
    original: 12,
  },
  {
    id: 2,
    photo: "/images/boy-shirt-2.webp",
    title: "Blue denim shirt",
    caption: "Manufactured by Louis",
    price: 10,
    original: 15,
  },
  {
    id: 3,
    photo: "/images/girl-kurti-2.webp",
    title: "Festival kurti",
    caption: "Manufactured by A&D",
    price: 4,
    original: 9,
  },
  {
    id: 4,
    photo: "/images/men-tee.webp",
    title: "Man's summer t-shirt ",
    caption: "Manufactured by A&D",
    price: 7,
    original: 12,
  },
  {
    id: 5,
    photo: "/images/girl-kurti.webp",
    title: "All season dress",
    caption: "Manufactured by reshma",
    price: 10,
    original: 14,
  },
  {
    id: 6,
    photo: "/images/white-tee.webp",
    title: "White college t-shirt",
    caption: "Manufactured by Allen solly",
    price: 6,
    original: 12,
  },
];
